Guidelime.registerGuide(
[[
[N 53-55 Felwood]
[GA Alliance]
[D Made from Hakurai's Video Guide\\ https://twitch.tv/hakurai \\ Our guild is recruiting! \\ https://www.guilded.gg/KOABD]
Start killing mobs in excess and as you travel, without Silithus in the game at launch, you will have to make up the xp some how!
We're roughly 20 more hours /played until you're 60. Grats![OC]
Open the crate in your bags for A little Slime Goes a Long Way quest to get 12 empty vials.[OC]
[G41,67Felwood]Kill Cursed Ooze and use the jars on their corpse for [QC4512,1]
[G40,56]Kill Tainted Ooze and use the jars on the corpse for [QC4512,2]
[G39,58]Head to Jaedenar and kill the mobs you need for [QC5155]
[G51.2,82.2]Turn in[QT5155]
Accept[QA5157]
[G50.8,81.6]Accept[QA5249]
[G37,69]All the mobs you need to kill are in this area. The shadowstalkers are stealthed. 
[G32,67]Kill Xavathras for [QC4421,4]
Finish killing the Satyr for [QC4421,1] [QC4421,2] [QC4421,3]
[G35,60]There's a moonwell here, use the empty canteen in your inventory to complete[QC5157]
[G51.2,82.2]Turn in[QT5157]
Accept[QA5158]
In the house, turn in[QT4421]
Accept[QA4906]
[G41,42]There are 5 craters here, kill 2 beasta and 2 horrors for [QC5156] - make sure you go into the crater for completion credit.
[G39,22]Kill Xavaric first for a quest item drop. Accept his quest for [QA939]
Finish killing Satyr for [QC939] and [QC4906]
[G56,18]Kill Warpwood elementals and loot for [QC4101]
[G62.4,24.2]Grab the flightpath
[V]Use the vendor to the south to clear your bags
[G64.8,8.2]Turn in[QT8462]
Accept[QA8465]
Accept[QA8461]
[G61,10]Kill Deadwood Furbolg for [QC8461]
Make sure you reach Unfriendly with Timbermaw Hold if you aren't already[OC]
If a totem drops, save it for later, you need to be Neutral to turn it in.[OC]
[G63.8,9]Turn in[QT8461]
Head into the cave, follow the path, once you hit the fork head east.[OC]
[G27.8,34.4Winterspring]Turn in[QT8465]
[G31,45]Turn in[QT980]
[QT3908]
Accept[QA3909]
Suicide to the closest mobs you can find and spirit rez, we're about to do a lot of flying to the debuff doesn't matter[OC]
[G61,38Winterspring]Accept [QA6604]
Accept[QA6603]
[G60.8,37.8][V]Sell trash, alchemists buy Major Healing Potion Recipe if you can[OC]
[G62.2,36.6]Grab the flightpath
Fly to Feathermoon, super long flight[OC]
Head back up the big tree and turn in[QT3791]
Alchemists train here if you need to[OC]
Swim into Feralas[OC]
[G42,25Feralas]Turn in[QT4142]If you didn't yet[OC]
[V]Buy some bait from him for The Videre Elixir quest[OC]
[G44,10]Place the bait down the stairs to lure the Gnoll away, then run inside to loot the Evoroot[OC]
[G42,45]Talk to Gregan and exchange the Evoroot for a Videre Exlixir[OC]
[H]Hearth to Menethil
Fly to Ironforge
IF YOU SEE A CENARION EMISSARY WITH A GREYED OUT QUEST IN FRONT OF THE FLIGHTMASTER -- That means that the Silithid quests will be available for the last part of the guide to 60, otherwise you'll have to use the alternate guide that will also be included.[OC]
[G71.6,16.4Ironforge]Accept [QA3371] if you don't have it
[G75.6,23]Turn in[QT4512]
Accept[QA4513]
Check the AH for 2 Thorium Bars and a Mithril Casing if you still don't have them[OC]
Fly to Thorium Point - you are going to be doing some elite quests, so try to find help if you can, or prepare for tough fights[OC]
[G39,38.8Searing Gorge]Accept[QA3452]
Drop into the Slag Pits from the crane, near the C in Cauldron on the map.[OC]
[G41,25]Kill your way north until you reach a room with a ramp. Turn in[QT3371]
Accept[QA3372]
Clear up the metal ramp and across the bridge to leave.[OC]
[G30.4,26.8]Hug the mountains to the north and eventually you'll find a path up towards the Twilight Mobs. Kill them and loot for [QC3452]
[G29,26]Loot the Artifact in the middle of the lava, you will have to clear around the lava pit first [QC3372]
Accept[QA3377]
Talk through his dialogue for [QC3377]
Turn in[QT3377]
Accept[QA3378]
Kill elites for the drop for [QC3378]
[G39,38.8]Turn in[QT3452]
Accept[QA3453]
Watch the roleplay then turn in[QT3453]
Accept[QA34534]
Loot the floaty thing for [QC3454]
Turn in[QT3454]
Accept[QA3462]
Turn in[QT3462]
Accept[QA3463]
You have to equip the Torch before lighting the flames on top of each of the towers[OC]
[G33,54]Light the flame for [QC3463,4]
[G35,60]Light the flame for [QC3463,1]
[G43,60]Go across the bridge, Light the flame for [QC3463,2]
[G49,54]Light the flame for [QC3463,3]
You may need help for the next step[OC]
[G73.2,76.6]Kill the elite Margol the Rager and loot the horn that he drops for [QA3181]
[G39,38.8]Turn in[QT3463]
Open the chest on the ground to accept[QA3481]
Turn it in at the chest for[QT3481]
This gives you a chest with an item inside that you need later, don't throw it away![OC]
Drop back into the Slag pits from the crane and clear north towards the dead dwarf[OC]
[G41,25]Turn in[QT3372]
Head back to Thorium Point and then fly to Thelsamar.
[G18.2,84Loch Modan]Turn in[QT3181]
Accept[QA3182]
Go back to the flightmaster and fly to Ironforge[OC]
[G71.6,16.4Ironforge]Turn in[QT3182]
Accept[QA3201]
Last chance to check for Mithril casing and 2x Thorium Bars[OC]
Fly back to Thelsamar
[G18.2,84Loch Modan]Turn in[QT3201]
Back to the flightmaster, fly to Menethil Harbor, DONT USE YOUR HEARTHSTONE[OC]
Take the boat to Auberdine from the north docks.[OC]
Fly to Talonbranch Glade in Felwood[OC]
Run back through the Timbermaw Hold tunnel to get to Winterspring[OC]
[G31,45Winterspring]Turn in[QT3909]
Turn in[QT6603]
Accept[QA3912]
[H]Hearth back to Menethil
Take the boat to Theramore[OC]
Fly to Ratchet[OC]
[G62.4,38.6]Turn in[QT4502]
Ride south out of Ratchet along the coast[OC]
[G65.8,43.8]Turn in[QT5158]
After the RP, accept [QA5159]
Go back to the flightmaster and Fly to Gadgetzan
[G50.8,27Tanaris]Accept[QA4507]
[G54,28.8]Just east of Gadgetzan, use the Videre elixir in the graveyard to kill yourself.[OC]
[G54,24]DO NOT REZ YET - Run straight north to find a ghost NPC, talk to him to turn in[QT3912]
Accept[QA3913]
Go back to your body and rez.
[G53,29]Touch the gravestone in the graveyard for [QT3913]
Accept[QA3914]
Grab a jungle remedy you saved from before if you have one, and the mithril casing, if you don't have them it's ok[OC]
Ride to Un'Goro Crater[OC]
[G71,75Un'Goro Crater]Accept[QA4301]
Accept[QA4292]
While doing the next steps, look for Un'Goro Soil, and kill Oozes and use the sample jar on them. If you did Haze of Evil for Sunken Temple, loot 3 Blood Petal Sprouts.[OC]
You may need help for this quest[OC]
[G44,81]Clear all the way west in the Hive to the far west round room.[OC]
Just the Jungle Remedy to clear the debuff if you have it.
Use the Lure on the crystal in the room. It spawns waves of enemies, as you kill the first wave run out of the room before the last one dies so they wont aggro you.[OC]
Finish the waves and loot the queen for [QC4507]
[G44,8]Try to finish killing the ooze on the way to the next point.[QC4513][OC]
Turn in [QT3914]
Accept[QA3941]
Turn in the Sunken Temple quest Haze of Evil and the follow up if you did them on top of the hill in Marshall's Refuge[OC]
[V]Sell trash
Run to the back of the cave and turn in[QT3941]
Accept[QA3942]
[G46.6,13.4]Accept[QA4243]
[G68,12]Work through the cave, in the back you'll find U'cha, kill him for [QC4301]
[G67,18]Turn in[QT4243]
Accept[QA4244] if you have the mithril casing[OC]
Turn in [QT4244][OC]
Accept[QA4245] if you're able to.
Escort A-Me for [QC4245]
Turn in[QT4245]
Finish [QC4513] if you didn't.
Grind until your Hearthstone is off CD if you need to.
[G79,49]Use the meat on the rock and put Pheramones on it. Kill him for [QC4292]
[G71,75]Turn in[QT4301]
Turn in[QT4292]
{H]Hearth to Menethil Harbor
Take the Boat to Auberdine[OC]
[G55.4,92Teldrassil]Accept[QA978]
Upstairs, accept[QA5250]
Take the teleporter into Darnassus[OC]
[G38.4,80.8Darnassus]Upstairs, turn in[QT4090]
[G34.8,8.8]Turn in[QT3790]If you didn't earlier.
Accept[QA3764]
[G31.6,7.8]Outside, turn in[QT3764]
Run back up the tree to the Archdruid and accept [QA3781]
If you have the Morrowgrain now, you can go downstairs and turn it in on the middle level, otherwise we will be back here later.[OC]
[G67.4,15.2]Set your hearthstone to Darnassus
[V]Sell trash
Fly to Astranaar
Ride east and then north back to Felwood[OC]
[G54,86Felwood]Turn in[QT4101]
Take the Cenarian Beacon from her. It will let you collect shards from  monsters and gathering material. The first turn in of each type allow you to unlock the world buffs and consumables.
Kill everything around you until you get 6 corrupted soul shards.
Turn it in for the Plant Salve back at the NPC that you turned the quest into.
Keep an eye out for a Corrupted Songflower during the rest of the guide to get a good buff.[OC]
[G51.2,82.22]Turn in[QT5159]
Accept[QA5165]
[G51.4,81.6]Turn in[QT939]
Accept[QA4441]
Turn in[QT3942]
Accept[QA4084]
Turn in[QT4906]
[G50.8,81.6]Turn in[QT5156]
Head straight north, kill wolves and bears to loot claws for [QC4084,1]
You may need help for the next part, especially if you don't have a songflower buff.[OC]
[G35,60]Head inside the cave[OC]
Grind on mobs inside until they drop a Blood Red Key[OC]
[G36,56]Extinguish the flame for [QC5165,1]
[G37,55]Up the ramp, extinguish for [QC5165,4]
[G37,53]Extinguish for [QC5165,3]
Nearby extinguish for [QC5165,2]
Accept[QA5202] from the key
Turn in the key to the night elf in the cage near the first Brazier[QT5202]
THIS IS AN EXTREMELY HARD ESCORT. YOU PROBABLY NEED HELP. The escort is underleveled and charges into everything. Pull with Line of Sight and pull ahead of her to keep from getting swarmed. She heads towards the last Brazier.[OC]
Accept[QA5203]
Once she puts on her armor 3 felguards are summoned.[OC]
At the exit, an elite will spawn and aggro you at the top.[OC]
Complete[QC5203]
[G50,16]Kill the treants for [QC4084,2]
[G62.2,25.6][V]Sell trash
Grind to level [XP55] on the Deadwood Furbolg if you aren't yet.
[NX 55-56 Winterspring]
]],"Hakurai - by Shikushiku")