Guidelime.registerGuide(
[[
[N 30-30 Warlock Class Quest]
[GA Warlock]
[D Warlock Class Quest for the Felhunter \\ Both Ally and Horde included!]
[G48.2,45.6Orgrimmar]Head to Gan'rul in the Cleft of Shadows to Accept[QA2996][A Orc]
Fly to Ratchet[A Orc]
[G62.6,35.4The Barrens]Turn in[QT2996][A Orc]
Fly back to Org and tack a Zeppelin to Undercity[A Orc]
[G76,37.4Undercity]Turn in[QT1801][A Orc]
Accept[QA1803][A Orc]
Fly to Tarren Mill[A Orc]
[G27.8,72.8Hillsbrad Foothills]Loot the tome for [QC1803,1][A Orc]
Fly to Gadgetzan if you have the flightpath, then ride north into Thousand Needles -- Otherwise Fly to Crossroads and run South[A Orc]
[G43.4,32.7Thousand Needles]In the cave, branch right and follow the path to the waterfall, look for the 'damaged chest'[QC1803][A Orc]
[G76,37.4Undercity]Back to Undercity, turn in[QT1803][A Orc]
Accept[QA1805][A Orc]
Fly to Tarren Mill or Hammerfall[A Orc]
[G55,54Wetlands]Head south to the Wetlands and kill Orcs in the area for [QC1805][A Orc]
Fly back to Undercity, take the Zeppelin to Org, and Fly to Ratchet[A Orc]
[G62.6,35.4The Barrens]Turn in[QT1805][A Orc]
Accept[QA1795][A Orc]
Nearby, summon the Felhunter and kill it to complete [QC1795][A Orc]
Turn in[QT1795][A Orc]
[G25.2,78.6Stormwind City]Accept[QA1798]at the Slaughtered Lamb[A Alliance]
[G62.6,35.4The Barrens]Turn in[QT1798][A Alliance]
Accept[QA1758][A Alliance]
Fly to Theramore, take the boat to Menethil Harbor, Fly to Ironforge[A Alliance]
[G74.2,9.6Ironforge]Turn in[QT1758][A Alliance]
Accept[QA1802][A Alliance]
Fly to Menethil Harbor, take the boat to Theramore, Fly to Ratchet[A Alliance]
Follow the main road south to Thousand Needles and take the elevator down, careful for the guards[A Alliance]
[G43.4,32.7Thousand Needles]In the cave, branch right and follow the path to the waterfall, look for the 'damaged chest'[QC1802,2][A Alliance]
Either head Southeast to Gadgetzan, or back up the elevator and to ratchet, if you go to Gadgetzan grab the flightpath.[A Alliance]
Fly to Theramore[A Alliance]
Take the boat the Menethil Harbor[A Alliance]
Get to Hillsbrad Foothills, Fly to Southshore if you have it, or Refuge Point if you don't[A Alliance]
[G27.8,72.8Hillsbrad Foothills]Loot the tome for [QC1802,1][A Alliance]
Fly back to Ironforge[A Alliance]
[G74.2,9.6]Turn in[QT1802][A Alliance]
Accept[QA1804][A Alliance]
Fly to Menethil Harbor[A Alliance]
[G55,54Wetlands]Head south to the Wetlands and kill Orcs in the area for [QC1804][A Alliance]
Head back to Menethil, take the boat to Theramore, Fly to Ratchet[A Alliance]
[G62.6,35.4The Barrens]Turn in[QT1804]
Accept[QA1795][A Alliance]
Nearby, summon the Felhunter and kill it to complete [QC1795][A Alliance]
Grats you have a dog of sorts!
]],"Class Quests- by Shikushiku")