Guidelime.registerGuide(
[[
[N 30-30 Undead Warlock Class Quest]
[GA Warlock]
[D Warlock Class Quest for the Felhunter \\ UNDEAD VERSION!]
[G83,27Undercity]Head to Carendin in The Undercity to accept[QA3001][A Horde]
Take a Zeppeplin to Org, then Fly to Ratchet[A Horde]
[G62.6,35.4The Barrens]Turn in[QT3001][A Horde]
Fly back to Org and tack a Zeppelin to Undercity[A Horde]
[G76,37.4Undercity]Turn in[QT1801][A Horde]
Accept[QA1803][A Horde]
Fly to Tarren Mill[A Horde]
[G27.8,72.8Hillsbrad Foothills]Loot the tome for [QC1803,1][A Horde]
Fly to Gadgetzan if you have the flightpath, then ride north into Thousand Needles -- Otherwise Fly to Crossroads and run South[A Horde]
[G43.4,32.7Thousand Needles]In the cave, branch right and follow the path to the waterfall, look for the 'damaged chest'[QC1803][A Horde]
[G76,37.4Undercity]Back to Undercity, turn in[QT1803][A Horde]
Accept[QA1805][A Horde]
Fly to Tarren Mill or Hammerfall[A Horde]
[G55,54Wetlands]Head south to the Wetlands and kill Hordes in the area for [QC1805][A Horde]
Fly back to Undercity, take the Zeppelin to Org, and Fly to Ratchet[A Horde]
[G62.6,35.4The Barrens]Turn in[QT1805][A Horde]
Accept[QA1795][A Horde]
Nearby, summon the Felhunter and kill it to complete [QC1795][A Horde]
Turn in[QT1795][A Horde]
]],"Class Quests- by Shikushiku")