Guidelime.registerGuide(
[[
[N 51-53 Un'Goro Crater]
[GA Alliance]
[D Made from Hakurai's Video Guide\\ https://twitch.tv/hakurai \\ Our guild is recruiting! \\ https://www.guilded.gg/KOABD]
[G51,26Tanaris]Turn in[QT2641]
Accept[QA2661]
[G50.8,27]Turn in[QT4493]
Accept[QA4496]
[G51.6,26.8]Accept[QA4504]
[G51,28]Turn in[QT2661]
Accept[QA2662]
Turn in[QT2662]
[G52.4,27.8]Set hearth to [S Gadgetzan]
[G53,46]Turn in[QT3444]
Accept[QA3446]
[G71,75Un'Goro Crater]Accept[QA4289]
Accept[QA4290]
Keep an eye out for crystals, we need 7 red, 7 blue, 7 green, and 7 yellow crystals total. You also want around 60 Un'Goro soil[OC]
[G63,68]Accept[QA3844]
Under the water near the raft, loot the sack for [QT3844]
Accept[QA3845]
[G68,57]Loot the corpse for [QT4290]
[G71,75]Turn in[QT4290]
Accept[QA4291]
You need to go to the raptor nests and kill regular raptors until a mate appears. You need two glands total.[OC]
[G60,72]Nest 1[OC]
[G62,65]Nest 2[OC]
[G63,77]Nest 3[OC]
[G67,73]Nest 4[OC]
[G67,67]Nest 5[OC]
Make sure you finished [QC4291]
Make sure you have 28 power crystals before continuing, 7 of each color[OC]
[G44.4,11.8]Accept[QA4503]
[G43,9.4]Accept[QA4141]
Open the bag you looted from the water now to loot the quest items needed.[OC]
[G44,8]Turn in[QT3845]
From the wanted poster, accept [QA4501]
[G43.8,7.2]Turn in the Journal if you looted it from mobs.
Acceept[QA3881]
Accept[QA3883]
[G43.6,7.4]Accept[QA3882]
Go inside and head to the back until you find the gnome, accept [QA4284]
Turn in[QT4284]
Accept[QA4287]
Accept[QA4285]
Accept[QA4288]
Head out of the cave and clear up your bags[OC]
Kill Blood Petals while completing the next steps[OC]
[G56,12]Talk to the Pylon to complete [QC4285]
Kill all of the Pterrodax in the area[OC]
[G64,17]Kill Apes for the different pelts, Thunderers are only found inside the cave. Complete[QC4289]
Head southeast and kill bloodpetal on the way until you finish [QC4141]
Kill Diemetradon on the way for Shizzles Flyer[OC]
[G69,37]Loot the crate for Expedition Salvation
[G77,50]Loot the pylon for [QC4287]
[G71,75]Turn in[QT4291]
Turn in[QT4289]
[G49,85]Grind mobs that you need for quests, and head into the Silithid Lair, make sure to interrupt the Silithid before they cast the disease on you.[OC]
[G49,85]Inside the round room, use the Scraping Jar for [QC3883]
Keep killing silithid for the Scent Gland for [QC4496,1]
[G44,90]Kill the Pterrodax south in the mountains for [QC4501,1] and [QC4503,2]
Go northwest of the Silithid and kill mobs for [QC4141] and [QC4503,1]
[G38,67]Loot the crates for [QC3991,2]
[G30,50]Accept[QA974]
Head straight west into the mountains, killing all the Frenzied Pterrodax you see[OC]
[G23,59]Loot the Pylon for [QC4288]
Rotate between the mountains and the wilderness until you complete [QC4501] and [QC4503]
Make sure you finished [QC3882]
[G44.4,11.8]Turn in[QT4503]
Turn in[QT4501] at Spraggle Frock the goblin
Accept[QA4492]
[G43,9.4]Turn in[QT4141]
Accept[QA4142]
[G43.8,7.2]Turn in[QT3883]
Turn in[QT3881]
[G43.6,7.4]Turn in[QT3882]
Go to the back of the cave and turn in[QT4287]
Turn in[QT4285]
Turn in[QT4288]
Accept[QA4321]
Wait a moment then speak to him to turn in[QT4321]
[V]Head out of the cave and clear up your bags[OC]
[G44.6,8.2]Accept[QA3908]
Head east out of the camp to the smaller set of tar pits to kill lower level Tar elementals. Loot them for [QC4504]
You should have a minimum of 40 Un'Goro Soil, MORE IS BETTER[OC]
Head to the volcano in the center, kill elementals while moving for Volcanic Ash[OC]
[G51,42]This is the start of the path up the mountain[OC]
[G50,46]Use the thermometer on the pillar for [QC974]
Kill elemantals in the area to get 9 ash before doing the escort. [QC4502]
[G51,50]Turn in[QT4492]
Accept[QA4491]
Put the canteen on a hotkey bar. When the goblin passes out, you need to use the canteen to wake him up[OC]
Head back to Marshal's Refuge to Spraggle, next to the wanted poster to complete the quest.[QC4491]
Turn in[QT4491]
Grind to level [XP52] if you aren't yet. It is a requirement for the next steps.
[G30,50]Turn in[QT974]
Accept[QA980]
Ride Northwest and into Silithus[OC]
[G50.6,34.4Silithus]Grab the flightpath if it's there. 
There will be two versions of the guide, 1 if Cenarion Hold is live and there are quest givers there, and a second version if there is no Cenarion Hold.[OC]
If you DON'T want to do Sunken Temple, Hearth to Gadgetzan and skip the next section. There will be a note in the guide of where to skip to.[OC]
ST - If you want to try to do Sunken Temple, Fly the Feathermoon to grab a quest[OC]
ST -  When  you land in Feathermoon, run up the big tree and accept [QA3791][OC]
ST - [V]Buy 2 stacks of seeds from Quintis. [OC]
ST - From now on you need to use the pouch from accepting the quest on cooldown, it has a chance of giving you morrowgrain which  is a requirement for 2 quests[OC]
ST - [G42,25Feralas]Turn in[QT4142][OC]
ST - Accept [QA4143][OC]
ST - [H]Hearth back to Gadgetzan and start looking for a Sunken Temple group[OC]
PEOPLE WHO SKIPPED THE ST SECTION, REJOIN THE GUIDE NOW[OC]
[G50.8,27Tanaris]Turn in[QT4496]
[G51.6,26.8]Turn in[QT4504]
Fly to Theramore Isle
[T]Train your first aid if you can inside the keep.
Ride the Boat to Menethil Harbor[OC]
Fly to Ironforge[OC]
[T]Train  your level 52 skills
[G75.6,23Ironforge]Accept[QA4512]
[G31,4]Turn in[QT3461]
[G18.6,51.6]Accept [QA3790]
[V]Sell your trash
Check the AH for 2 thorium bars and a Mithril Casing if you still don't have them[OC]
Fly back to Menethil Harbor[OC]
Set your hearthstone to Menethil Harbor
Take the northern boat to Auberdine in Darkshore[OC]
Players who DID pickup the ST quests need to skip the next part. This next part is only if you SKIPPED picking up the ST quests[OC]
SKIPPED - Fly to Rut'theran Village and take the teleporter to Darnassus[OC]
SKIPPED - [G34.8,8.8Darnassus]Turn in Assisting Arch Druid Staghelm
SKIPPED - You should be able to turn in 20 Un'Goro soil for a quest around/from him and then accept a quest to get a pouch. From the person that gives you the pouch, buy 2 stacks of seeds. \\ You will need to use  the pouch on cool down for quests you will turn in later[OC]
SKIPPED - Go back through the Teleporter and head to the flight master.
BOTH TYPES OF PLAYERS REJOIN NOW[OC]
Fly to Astraanar
Ride East along the road until it forks north, then ride north into Felwood. Alliance has bad flight paths in this zone, so remember this run.[OC]
[G54,86Felwood]Accept[QA4101]
[G50,85]Accept Timbermaw Ally (Not sure which quest ID it is)
[G51.2,82.2]Accept[QA5155]
[G51.4,81.6]Accept[QA4421]
[G50.8,81.6]Accept[QA5156]
[G48,90]Kill Deadwood mobs for Timbermaw Ally[OC]
Make sure you finished Timbermaw Ally.[OC]
[G50,85]Turn in Timbermaw Ally[O]
Accept[QA8462]
Grind of the Timbermaw until you are level [XP53]. If you skipped any of the dungeons this will catch you up to anyone who completed them all.
[NX 53-55 Felwood]
]],"Hakurai - by Shikushiku")