local L = LibStub("AceLocale-3.0"):NewLocale("ClassicCastbars", "deDE")
if not L then return end

--[[
    Want to help translate ClassicCastbars?
    https://www.curseforge.com/wow/addons/classiccastbars/localization

    ** THE REST OF THIS FILE IS AUTOMATICALLY GENERATED **
]]

L["AUTO_POS_BAR"] = "Zauberbalken automatisch positionieren"
L["BORDER_COLOR"] = "Randfarbe auswählen"
L["CAST_BORDER"] = "Randtextur auswählen"
L["CAST_BORDER_TOOLTIP"] = "Textur einstellen die für den Rand des Zauberbalken genutzt wird."
L["CAST_FONT"] = "Schriftart des Zauberbalken auswählen"
L["CAST_FONT_TOOLTIP"] = "Schriftart einstellen die für den Zaubernamen und der Zeitanzeige genutzt wird."
L["CAST_STATUSBAR"] = "Zauberbalken-Textur auswählen"
L["CAST_STATUSBAR_TOOLTIP"] = "Texturtyp einstellen die für den Zauber- und Statusbalken genutzt wird."
L["CASTBAR"] = "Zauberbalken"
L["CASTBAR_COLORS"] = "Zauberbalken-Farben"
L["CASTBAR_ICON"] = "Zauberbalken-Symbol"
L["CASTBAR_SIZING"] = "Zauberbalken-Größe"
L["CASTBAR_TEXTURE_FONT"] = "Zauberbalken-Texturen"
L["DEFAULT"] = "Standard"
L["FONT_SIZE"] = "Schriftgröße"
L["FONT_SIZE_TOOLTIP"] = "Schriftgröße einstellen die für den Zaubernamen und der Zeitanzeige genutzt wird."
L["GENERAL"] = "Allgemeine Einstellungen"
L["HEIGHT"] = "Höhe des Zauberbalken"
L["HEIGHT_TOOLTIP"] = "Höhe des Zauberbalken einstellen."
L["ICON_HIDE_BORDER"] = "Symbolrand verstecken"
L["ICON_POS_X"] = "Symbol-Position X"
L["ICON_POS_Y"] = "Symbol-Position Y"
L["ICON_SHOW"] = "Zaubersymbol anzeigen"
L["ICON_SIZE"] = "Symbolgröße"
L["ICON_SIZE_TOOLTIP"] = "Größe für das Zauberleistensymbol einstellen."
L["LSM_TEXTURE_NOTE"] = "Wichtig: Falls du eigene/fremde Texturen/Schriftarten benutzt, diese aber später wieder von deinem PC löschen tust, dann solltest du hier manuell die Texturen oder Schriftarten zurücksetzen damit das Addon wieder normal weiter arbeiten kann."
L["NAMEPLATE"] = "Namensplakette"
L["PARTY"] = "Gruppe"
L["PLAYER"] = "Spieler"
L["REQUIRES_RESTART"] = "Die Deaktivierung dieses Zauberbalken-Moduls benötigt ein Neuladen der Oberfläche. Drücke auf Annehmen um die Benutzeroberfläche neuzuladen."
L["RESET_ALL"] = "Einstellungen zurücksetzen"
L["SHOW_SPARK"] = "Zauberbalken-Funkeneffekt anzeigen"
L["SHOW_TIMER"] = "Zeitanzeige anzeigen"
L["SHOW_TIMER_TOOLTIP"] = "Zeigt für den momentanen Zauber eine Zeitanzeige an."
L["STATUS_BG_COLOR"] = "Hintergrundfarbe auswählen"
L["STATUS_CHANNEL_COLOR"] = "Kanalisierungsfüllfarbe auswählen"
L["STATUS_COLOR"] = "Zauberfüllfarbe auswählen"
L["STATUS_FAILED_COLOR"] = "Fehlgeschlagene Zauberfüllfarbe auswählen"
L["STATUS_UNINTERRUPTIBLE_COLOR"] = "Füllfarbe für nicht unterbrechbare Zauber auswählen"
L["TARGET"] = "Ziel"
L["TEST"] = "Testmodus für"
L["TEST_MODE_DRAG"] = "Testmodus - ziehen zum bewegen"
L["TEXT_COLOR"] = "Textfarbe auswählen"
L["TEXT_POS_X"] = "Text-Position X"
L["TEXT_POS_Y"] = "Text-Position Y"
L["TOGGLE_CASTBAR"] = "Zauberbalken aktivieren"
L["WIDTH"] = "Breite des Zauberbalken"
L["WIDTH_TOOLTIP"] = "Breite des Zauberbalken einstellen."

